

services:
  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    env_file:
      - .env
    ports:
      - '5000:5000'
    volumes:
      - .:/app
    depends_on:
      - mongo
    environment:
      - MONGO_URI=${MONGO_URI}
      - PORT=5000
  
  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
  
volumes:
  mongo-data: {}
    